AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: >
  This tempalte creates the macro that will perform pre-processing


Parameters:

  LambdaRuntime:
    Type: String
    Default: python3.8
    Description: Python macro runtime


Resources:

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: sqlserverdevfabric-macro
      Description: Processes the template and creates multiple instances of the Service resource
      FunctionName: !Ref AWSMacroFunction

  AWSMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sqlserverdevfabric-lambda-macro
      CodeUri: src
      Handler: index.handler
      Runtime: !Ref LambdaRuntime
      Timeout: 360
      Role: !GetAtt AWSMacroFunctionExecutionRole.Arn

  AWSMacroFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
     AssumeRolePolicyDocument:
       Statement:
       - Action:
         - sts:AssumeRole
         Effect: Allow
         Principal:
           Service:
           - lambda.amazonaws.com
       Version: '2012-10-17'
     Path: "/"
     Policies:
     - PolicyDocument:
         Statement:
         - Action:
           - logs:CreateLogGroup
           - logs:CreateLogStream
           - logs:PutLogEvents
           Effect: Allow
           Resource: arn:aws:logs:*:*:*
         Version: '2012-10-17'
       PolicyName: !Sub ${AWS::StackName}-AWSMacroFunction-CW
