AWSTemplateFormatVersion: '2010-09-09'
Description: Data plane


Transform:
  - sqlserverdevfabric-macro


Metadata:
  AWS::CloudFormation::Interface:

    ParameterLabels:

      ClusterName:
        default: "ECS Cluster name"

      DBInstancesCount:
        default: "SQL Instance count"

      CloudWatchLogGroup:
        default: "Cloud Watch Log Group name"

      ImageUrl:
        default: "SQL Server docker image"

      TaskCPU:
        default: "Server CPU shares"

      TaskMemory:
        default: "Server RAM Memory (MB)"

      UseSpot:
        default: "Enable Fargate Spot for this setup"

      MSSQLCOLLATION:
        default: "Collation and Unicode support"

    ParameterGroups:
      -
        Label:
          default: "Service settings ..."
        Parameters:
          - ClusterName
          - DBInstancesCount
          - CloudWatchLogGroup
      -
        Label:
          default: "SQL Server configuration ..."
        Parameters:
          - ImageUrl
          - TaskCPU
          - TaskMemory
          - UseSpot
          - MSSQLCOLLATION


Conditions:

  EnableSpot: !Equals [!Ref UseSpot, 'true']


Parameters:

  ClusterName:
    Type: String
    Default: sqlserverdevfabric-cluster
    Description: >
      Must match the ECS Cluster created by the Control Plane, were you
      intend to deploy the SQL Instances
    AllowedValues:
      - sqlserverdevfabric-cluster

  DBInstancesCount:
    Type: Number
    Description: >
      How many DB instances with the exact same configuration do you want to deploy?
    Default: 1

  CloudWatchLogGroup:
    Type: String
    Description: >
      Specify the destination Log Group in CloudWatch
    Default: /ecs/SQLServerFargate

  ImageUrl:
    Type: String
    Description: >
      SQL Server Docker image to deploy
    Default: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-18.04

  TaskCPU:
    Type: Number
    Description: >
      Allocated CPU shares for the container that will run the database engine. Please consider the following supported combinations: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
    Default: 2048
    AllowedValues:
      - 1024
      - 2048
      - 4096

  TaskMemory:
    Type: Number
    Description: >
      Allocated RAM memory for the container that will run the database engine. Please consider the following supported combinations: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
    Default: 8192
    AllowedValues:
      - 2048
      - 3072
      - 4096
      - 5120
      - 6144
      - 7168
      - 8192
      - 9216
      - 10240
      - 11264
      - 12288
      - 13312
      - 14336
      - 15360
      - 16384
      - 17408
      - 18432
      - 19456
      - 20480

  UseSpot:
    Type: String
    Description: >
      Choose if you want to use Fargate Spot technology
    Default: No
    AllowedValues:
      - Yes
      - No

  MSSQLCOLLATION:
    Type: String
    Default: SQL_Latin1_General_CP1_CI_AS
    Description: SQL Server collation setting


Resources:

  ServiceStack:
    Type: AWS::CloudFormation::Stack
    Count: !Ref DBInstancesCount
    Properties:
      TemplateURL: fargate-sql-service/fargate-sql-service.yaml
      Parameters:
        ClusterName: !If
          - EnableSpot
          - Fn::ImportValue: !Sub '${ClusterName}::TheECSClusterSpot'
          - Fn::ImportValue: !Sub '${ClusterName}::TheECSCluster'
        TheVPCID:
          Fn::ImportValue:
            !Sub '${ClusterName}::TheVPCID'
        DefaultAccessCIDR:
          Fn::ImportValue:
            !Sub '${ClusterName}::TheVPCCIDR'
        SubnetsPrivate:
          Fn::ImportValue:
            !Sub '${ClusterName}::SubnetsPrivate'
        SRVPrefix: db-%s
        ServiceDiscoveryNamespace:
          Fn::ImportValue:
            !Sub '${ClusterName}::ServiceDiscoveryNamespace'
        EFSID:
          Fn::ImportValue:
            !Sub '${ClusterName}::EFS'
        CloudWatchLogGroup: !Ref CloudWatchLogGroup
        ImageUrl: !Ref ImageUrl
        ContainerPort: 1433
        TaskCPU: !Ref TaskCPU
        TaskMemory: !Ref TaskMemory
        MSSQLCOLLATION: !Ref MSSQLCOLLATION
